version: '3.8'
services:
  api:
    container_name: api
    build: .
    command: node mainScripts/app.js
    ports:
      - 5001:5001
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
    restart: on-failure
